"""Sanity-check every generated file and write docs/data_check.md.

Three questions, in order:

  1. Is the data WELL FORMED?   row counts, nulls, value domains.
  2. Does it JOIN?              every foreign key resolves, no orphans or dupes.
  3. Are the PLANTED PATTERNS actually there? The whole point of the synthetic
     dataset is that specific signals were designed into it (disputes run
     negative, new hires score lower, Team 3 improves late, CSAT tracks
     sentiment). If a generator is retuned and a pattern washes out, the
     downstream NLP work and the Power BI story quietly stop making sense --
     so each one is asserted here with a numeric threshold.

Thresholds are deliberately loose: they are set to catch a pattern
DISAPPEARING, not to pin down the exact number a given seed produces.

Exits non-zero if any check fails, so this doubles as a CI gate.

All data is SYNTHETIC (see CLAUDE.md). Run from the project root:
    python src/check_data.py
"""

import re
import sys
from datetime import date
from pathlib import Path

import pandas as pd

RAW = Path("data/raw")
REPORT_PATH = Path("docs/data_check.md")

# Same fixed "today" the generators use.
REFERENCE_DATE = date(2026, 10, 4)

# Design constants mirrored from the generators, so this file can check them.
N_AGENTS = 20
N_INTERACTIONS = 2_000
IMPROVING_TEAM = "Move In / Move Out"  # "Team 3"
IMPROVEMENT_WINDOW_DAYS = 60
IMPROVEMENT_MONTHS = ["2026-08", "2026-09"]
NEW_HIRE_DAYS = 180
REPEAT_WINDOW_DAYS = 7
WORST_TOPIC = "high bill dispute"

VALID_SENTIMENTS = {"positive", "neutral", "negative"}
VALID_CHANNELS = {"voice", "chat", "email"}
VALID_STATUSES = {"closed", "open", "escalated"}
CHANNEL_TARGET = {"voice": 0.65, "chat": 0.25, "email": 0.10}


def fmt_cell(value):
    """Readable cell text for the markdown report."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    if isinstance(value, pd.Timestamp):
        return value.date().isoformat()
    if isinstance(value, float):
        # Trim trailing zeros, but keep one decimal so 71.0 stays "71.0"
        # (plain "71" would read like an integer count).
        text = f"{value:,.3f}".rstrip("0")
        return text + "0" if text.endswith(".") else text
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def md_table(df):
    """Render a DataFrame as a markdown table.

    Hand-rolled rather than using DataFrame.to_markdown() because that needs
    `tabulate`, which is not in requirements.txt -- the report should not add a
    dependency just to draw a box.
    """
    frame = df.reset_index()
    headers = [str(c) for c in frame.columns]
    rows = [[fmt_cell(v) for v in row] for row in frame.itertuples(index=False, name=None)]
    widths = [
        max([len(h)] + [len(r[i]) for r in rows])
        for i, h in enumerate(headers)
    ]
    out = ["| " + " | ".join(h.ljust(w) for h, w in zip(headers, widths)) + " |",
           "| " + " | ".join("-" * w for w in widths) + " |"]
    for r in rows:
        out.append("| " + " | ".join(c.ljust(w) for c, w in zip(r, widths)) + " |")
    return "\n".join(out)


class Report:
    """Collects pass/fail checks and markdown fragments for the report."""

    def __init__(self):
        self.lines = []
        self.results = []  # (section, name, passed, detail)
        self._section = "general"

    def section(self, title):
        self._section = title
        self.lines.append(f"\n## {title}\n")

    def text(self, body):
        self.lines.append(body)

    def table(self, df, caption=None):
        """Render a DataFrame as a markdown table."""
        self.lines.append("")  # close any preceding bullet list
        if caption:
            self.lines.append(f"**{caption}**\n")
        self.lines.append(md_table(df))
        self.lines.append("")

    def check(self, name, passed, detail=""):
        """Record one assertion. `passed` is truthy/falsey, `detail` explains."""
        passed = bool(passed)
        self.results.append((self._section, name, passed, detail))
        mark = "PASS" if passed else "**FAIL**"
        self.lines.append(f"- {mark} — {name}" + (f" — {detail}" if detail else ""))
        return passed

    @property
    def failures(self):
        return [r for r in self.results if not r[2]]

    def render(self):
        passed = len(self.results) - len(self.failures)
        head = [
            "# Data check report",
            "",
            f"Generated by `src/check_data.py` against `data/raw/` "
            f"(reference date {REFERENCE_DATE.isoformat()}).",
            "All data is synthetic — see `CLAUDE.md`.",
            "",
            f"**{passed}/{len(self.results)} checks passed.**",
            "",
        ]
        if self.failures:
            head.append("Failing checks:")
            head += [f"- *{s}* — {n}" + (f" — {d}" if d else "") for s, n, _, d in self.failures]
            head.append("")
        return "\n".join(head + self.lines) + "\n"


def pct(x):
    """Format a 0-1 fraction as a percentage string."""
    return f"{x * 100:.1f}%"


def load():
    """Read all five files, failing loudly if the pipeline hasn't been run."""
    missing = [f for f in ["agents.csv", "interactions.csv", "cases.csv",
                           "csat_survey.csv", "sqm_monthly.csv"]
               if not (RAW / f).exists()]
    if missing:
        raise SystemExit(
            f"Missing {', '.join(missing)} in {RAW} -- run: python src/generate_all.py"
        )

    agents = pd.read_csv(RAW / "agents.csv", parse_dates=["hire_date"])
    interactions = pd.read_csv(RAW / "interactions.csv", parse_dates=["start_datetime"])
    cases = pd.read_csv(RAW / "cases.csv", parse_dates=["created_date", "closed_date"])
    survey = pd.read_csv(RAW / "csat_survey.csv", keep_default_na=False, na_values=[])
    sqm = pd.read_csv(RAW / "sqm_monthly.csv")
    # comment is free text where blank is meaningful, so it is read as "" not NaN.
    survey["csat_score"] = pd.to_numeric(survey["csat_score"])
    return agents, interactions, cases, survey, sqm


# --- 1. Shape ---------------------------------------------------------------

def check_row_counts(rep, agents, interactions, cases, survey, sqm):
    rep.section("1. Row counts")

    counts = pd.DataFrame(
        [
            ("agents.csv", len(agents), agents.shape[1], f"exactly {N_AGENTS}"),
            ("interactions.csv", len(interactions), interactions.shape[1], f"exactly {N_INTERACTIONS:,}"),
            ("cases.csv", len(cases), cases.shape[1], "~1,800 (1,600-2,000)"),
            ("csat_survey.csv", len(survey), survey.shape[1], "~15% of interactions (10-20%)"),
            ("sqm_monthly.csv", len(sqm), sqm.shape[1], "months x teams"),
        ],
        columns=["file", "rows", "columns", "expected"],
    ).set_index("file")
    rep.table(counts)

    rep.check("agents.csv has exactly 20 CCRs", len(agents) == N_AGENTS, f"{len(agents)} rows")
    rep.check("4 teams of 5 agents each",
              agents["team"].value_counts().eq(5).all() and agents["team"].nunique() == 4,
              f"{agents['team'].nunique()} teams, "
              f"{sorted(agents['team'].value_counts().unique())} agents per team")
    rep.check("interactions.csv has exactly 2,000 rows",
              len(interactions) == N_INTERACTIONS, f"{len(interactions)} rows")
    rep.check("cases.csv is close to 1,800 rows", 1_600 <= len(cases) <= 2_000,
              f"{len(cases)} rows ({len(cases) / len(interactions):.0%} of interactions)")

    rate = len(survey) / len(interactions)
    rep.check("survey response rate is near 15%", 0.10 <= rate <= 0.20,
              f"{pct(rate)} ({len(survey)} responses)")

    n_months = sqm["month"].nunique()
    rep.check("sqm_monthly.csv is one row per month x team",
              len(sqm) == n_months * agents["team"].nunique() and not sqm.duplicated(["month", "team"]).any(),
              f"{n_months} months x {agents['team'].nunique()} teams = {len(sqm)} rows")


def check_nulls(rep, agents, interactions, cases, survey, sqm):
    rep.section("2. Nulls and value domains")

    frames = {"agents": agents, "interactions": interactions, "cases": cases,
              "survey": survey, "sqm": sqm}
    null_rows = []
    for name, df in frames.items():
        for col in df.columns:
            n = int(df[col].isna().sum())
            if name == "survey" and col == "comment":
                n = int((df[col].astype(str).str.strip() == "").sum())
            null_rows.append((name, col, n, pct(n / len(df))))
    nulls = pd.DataFrame(null_rows, columns=["file", "column", "null_or_blank", "share"])
    rep.table(nulls[nulls["null_or_blank"] > 0].set_index(["file", "column"]),
              caption="Columns with nulls / blanks (everything else is 100% populated)")

    # closed_date is legitimately empty for work that hasn't finished; comment is
    # legitimately blank (people skip the free-text box). Nothing else may be null.
    expected_null = {("cases", "closed_date"), ("survey", "comment")}
    offenders = [(f, c, n) for f, c, n, _ in null_rows if n and (f, c) not in expected_null]
    rep.check("no unexpected nulls in any file", not offenders, str(offenders) if offenders else "")

    rep.check("every interaction has a transcript",
              (interactions["transcript_text"].astype(str).str.strip() != "").all())
    rep.check("closed cases always have a closed_date",
              cases.loc[cases["status"] == "closed", "closed_date"].notna().all())
    rep.check("open cases never have a closed_date",
              cases.loc[cases["status"] == "open", "closed_date"].isna().all())

    # Value domains.
    rep.check("true_sentiment ∈ {positive, neutral, negative}",
              set(interactions["true_sentiment"]) <= VALID_SENTIMENTS)
    rep.check("channel ∈ {voice, chat, email}", set(interactions["channel"]) <= VALID_CHANNELS)
    rep.check("case status ∈ {closed, open, escalated}", set(cases["status"]) <= VALID_STATUSES)
    rep.check("repeat_contact_7d ∈ {Y, N}", set(cases["repeat_contact_7d"]) <= {"Y", "N"})
    rep.check("resolved ∈ {Y, N}", set(survey["resolved"]) <= {"Y", "N"})
    rep.check("csat_score is an integer 1-5",
              survey["csat_score"].between(1, 5).all() and (survey["csat_score"] % 1 == 0).all())
    rep.check("handle_time_sec and hold_time_sec are non-negative",
              (interactions["handle_time_sec"] >= 0).all() and (interactions["hold_time_sec"] >= 0).all())
    rep.check("csat_target within 0.80-0.85", agents["csat_target"].between(0.80, 0.85).all())
    rep.check("aht_target_sec within 420-480", agents["aht_target_sec"].between(420, 480).all())
    rep.check("fcr_pct within 70-80", sqm["fcr_pct"].between(70, 80).all(),
              f"range {sqm['fcr_pct'].min()}-{sqm['fcr_pct'].max()}")
    rep.check("industry_benchmark_fcr_pct sits around 74",
              sqm["industry_benchmark_fcr_pct"].between(72, 76).all(),
              f"mean {sqm['industry_benchmark_fcr_pct'].mean():.1f}")

    # Dates must make sense.
    rep.check("no interaction is dated in the future",
              (interactions["start_datetime"].dt.date <= REFERENCE_DATE).all())
    rep.check("interactions fall on weekdays in business hours",
              interactions["start_datetime"].dt.dayofweek.le(4).all()
              and interactions["start_datetime"].dt.hour.between(7, 19).all())
    rep.check("closed_date never precedes created_date",
              (cases["closed_date"].dropna() >= cases.loc[cases["closed_date"].notna(), "created_date"]).all())
    rep.check("no case closed in the future",
              (cases["closed_date"].dropna().dt.date <= REFERENCE_DATE).all())


# --- 2. Key integrity -------------------------------------------------------

def check_integrity(rep, agents, interactions, cases, survey, sqm):
    rep.section("3. Key integrity")

    rep.check("interaction_id is unique", not interactions["interaction_id"].duplicated().any())
    rep.check("agent_id is unique", not agents["agent_id"].duplicated().any())
    rep.check("case_id is unique", not cases["case_id"].duplicated().any())
    rep.check("response_id is unique", not survey["response_id"].duplicated().any())

    orphan_agents = set(interactions["agent_id"]) - set(agents["agent_id"])
    rep.check("interactions.agent_id -> agents.agent_id", not orphan_agents,
              f"{len(orphan_agents)} orphans" if orphan_agents else "all 2,000 resolve")

    valid_interactions = set(interactions["interaction_id"])
    orphan_cases = set(cases["interaction_id"]) - valid_interactions
    rep.check("cases.interaction_id -> interactions.interaction_id", not orphan_cases,
              f"{len(orphan_cases)} orphans" if orphan_cases else f"all {len(cases)} resolve")
    rep.check("at most one case per interaction", not cases["interaction_id"].duplicated().any())

    orphan_survey = set(survey["interaction_id"]) - valid_interactions
    rep.check("csat_survey.interaction_id -> interactions.interaction_id", not orphan_survey,
              f"{len(orphan_survey)} orphans" if orphan_survey else f"all {len(survey)} resolve")
    rep.check("at most one survey response per interaction",
              not survey["interaction_id"].duplicated().any())

    orphan_teams = set(sqm["team"]) - set(agents["team"])
    rep.check("sqm_monthly.team -> agents.team", not orphan_teams,
              f"{orphan_teams}" if orphan_teams else "all 4 teams present")

    # case_type is supposed to mirror the interaction topic, which is what lets
    # the two files be used interchangeably for topic analysis.
    joined = cases.merge(interactions[["interaction_id", "topic", "true_sentiment",
                                       "start_datetime"]], on="interaction_id")
    mismatch = (joined["case_type"] != joined["topic"]).sum()
    rep.check("cases.case_type matches the interaction topic", mismatch == 0,
              f"{mismatch} mismatches")

    # Nobody can handle a contact before their first day.
    with_hire = interactions.merge(agents[["agent_id", "hire_date", "team"]], on="agent_id")
    before_hire = (with_hire["start_datetime"] < with_hire["hire_date"]).sum()
    rep.check("no interaction predates its agent's hire date", before_hire == 0,
              f"{before_hire} violations")

    # Each queue should be owned by exactly one team, or team-level routing in
    # Power BI would double-count.
    queue_teams = with_hire.groupby("queue")["team"].nunique()
    rep.check("each queue is owned by exactly one team", queue_teams.eq(1).all(),
              f"{queue_teams.size} queues")

    # repeat_contact_7d should be recomputable from the case log itself. A Power
    # BI measure that recalculates it must land on the same answer.
    contacts = cases.groupby("customer_id")["created_date"].apply(list).to_dict()
    recomputed = []
    for cust, created in zip(cases["customer_id"], cases["created_date"]):
        window_end = created + pd.Timedelta(days=REPEAT_WINDOW_DAYS)
        recomputed.append("Y" if any(created < d <= window_end for d in contacts[cust]) else "N")
    disagree = (pd.Series(recomputed, index=cases.index) != cases["repeat_contact_7d"]).sum()
    rep.check("repeat_contact_7d reconciles with the case log itself", disagree == 0,
              f"{disagree} rows disagree")

    rep.text("")
    cust_counts = cases["customer_id"].value_counts().value_counts().sort_index()
    cust_counts.index.name = "cases per customer"
    rep.table(cust_counts.rename("customers").to_frame(),
              caption=f"Customer reuse — {cases['customer_id'].nunique():,} customers across "
                      f"{len(cases):,} cases")
    rep.check("some customers have more than one contact",
              (cases["customer_id"].value_counts() > 1).sum() > 0,
              f"{(cases['customer_id'].value_counts() > 1).sum()} repeat customers")


# --- 3. Planted patterns ----------------------------------------------------

def check_patterns(rep, agents, interactions, cases, survey, sqm):
    rep.section("4. Planted patterns")

    merged = interactions.merge(agents, on="agent_id")
    merged["ramping"] = (merged["start_datetime"] - merged["hire_date"]).dt.days < NEW_HIRE_DAYS

    # --- Pattern 1: sentiment by topic ---------------------------------------
    rep.text("\n### 4.1 Sentiment by topic\n")
    by_topic = pd.crosstab(merged["topic"], merged["true_sentiment"], normalize="index")
    by_topic = by_topic[["negative", "neutral", "positive"]].round(3)
    by_topic["n"] = merged["topic"].value_counts()
    by_topic["mean_handle_sec"] = merged.groupby("topic")["handle_time_sec"].mean().round(0)
    rep.table(by_topic.sort_values("negative", ascending=False))

    neg = by_topic["negative"]
    rep.check(f"'{WORST_TOPIC}' is the most negative topic",
              neg.idxmax() == WORST_TOPIC, f"worst = '{neg.idxmax()}' at {pct(neg.max())}")
    rep.check(f"'{WORST_TOPIC}' is mostly negative (>60%)", neg[WORST_TOPIC] > 0.60,
              pct(neg[WORST_TOPIC]))
    aht = by_topic["mean_handle_sec"]
    rep.check(f"'{WORST_TOPIC}' has the longest handle time",
              aht.idxmax() == WORST_TOPIC,
              f"{aht[WORST_TOPIC]:.0f}s vs {aht.drop(WORST_TOPIC).mean():.0f}s elsewhere")

    # --- Pattern 2: new hires vs tenured ------------------------------------
    rep.text("\n### 4.2 New hires vs tenured agents\n")
    ramp = merged.groupby("ramping").agg(
        interactions=("interaction_id", "size"),
        pct_negative=("true_sentiment", lambda s: round((s == "negative").mean(), 3)),
        pct_positive=("true_sentiment", lambda s: round((s == "positive").mean(), 3)),
        mean_handle_sec=("handle_time_sec", "mean"),
    )
    ramp["mean_handle_sec"] = ramp["mean_handle_sec"].round(1)
    ramp.index = ramp.index.map({True: "new hire (<6 months)", False: "tenured"})
    ramp.index.name = "agent group"
    rep.table(ramp)

    if {"new hire (<6 months)", "tenured"} <= set(ramp.index):
        new_neg = ramp.loc["new hire (<6 months)", "pct_negative"]
        ten_neg = ramp.loc["tenured", "pct_negative"]
        rep.check("new hires see more negative sentiment than tenured agents",
                  new_neg - ten_neg >= 0.05,
                  f"{pct(new_neg)} vs {pct(ten_neg)} (+{(new_neg - ten_neg) * 100:.1f}pp)")
        new_aht = ramp.loc["new hire (<6 months)", "mean_handle_sec"]
        ten_aht = ramp.loc["tenured", "mean_handle_sec"]
        rep.check("new hires take longer per contact", new_aht > ten_aht,
                  f"{new_aht:.0f}s vs {ten_aht:.0f}s")
    else:
        rep.check("new-hire interactions exist in the window", False,
                  "no interactions handled while an agent was under 6 months tenure")

    # --- Pattern 3: Team 3 improvement --------------------------------------
    rep.text(f"\n### 4.3 '{IMPROVING_TEAM}' trend (Team 3)\n")
    merged["month"] = merged["start_datetime"].dt.to_period("M").astype(str)
    trend = merged[merged["team"] == IMPROVING_TEAM].groupby("month").agg(
        interactions=("interaction_id", "size"),
        pct_negative=("true_sentiment", lambda s: round((s == "negative").mean(), 3)),
        pct_positive=("true_sentiment", lambda s: round((s == "positive").mean(), 3)),
    )
    fcr = sqm[sqm["team"] == IMPROVING_TEAM].set_index("month")
    trend["fcr_pct"] = fcr["fcr_pct"]
    trend["benchmark"] = fcr["industry_benchmark_fcr_pct"]
    rep.table(trend)

    days_from_end = (pd.Timestamp(REFERENCE_DATE) - merged["start_datetime"]).dt.days
    team3 = merged[merged["team"] == IMPROVING_TEAM]
    last2 = team3[days_from_end.loc[team3.index] <= IMPROVEMENT_WINDOW_DAYS]
    earlier = team3[days_from_end.loc[team3.index] > IMPROVEMENT_WINDOW_DAYS]

    pos_lift = (last2["true_sentiment"] == "positive").mean() - (earlier["true_sentiment"] == "positive").mean()
    neg_drop = (earlier["true_sentiment"] == "negative").mean() - (last2["true_sentiment"] == "negative").mean()
    rep.check(f"'{IMPROVING_TEAM}' positive share rises in the last 2 months",
              pos_lift >= 0.10, f"+{pos_lift * 100:.1f}pp "
              f"({pct((earlier['true_sentiment'] == 'positive').mean())} -> "
              f"{pct((last2['true_sentiment'] == 'positive').mean())})")
    rep.check(f"'{IMPROVING_TEAM}' negative share falls in the last 2 months",
              neg_drop >= 0.05, f"-{neg_drop * 100:.1f}pp")

    # The improvement must also be visible in the scorecard a manager reads.
    t3_fcr = sqm[sqm["team"] == IMPROVING_TEAM]
    late = t3_fcr[t3_fcr["month"].isin(IMPROVEMENT_MONTHS)]["fcr_pct"].mean()
    early = t3_fcr[~t3_fcr["month"].isin(IMPROVEMENT_MONTHS)]["fcr_pct"].mean()
    rep.check(f"'{IMPROVING_TEAM}' FCR steps up in {'/'.join(IMPROVEMENT_MONTHS)}",
              late - early >= 3.0, f"{early:.1f}% -> {late:.1f}% (+{late - early:.1f}pp)")
    rep.check(f"'{IMPROVING_TEAM}' crosses the industry benchmark only late",
              early < t3_fcr["industry_benchmark_fcr_pct"].mean() < late,
              f"benchmark {t3_fcr['industry_benchmark_fcr_pct'].mean():.1f}%")

    rep.text("")
    rep.table(sqm.pivot_table(index="month", columns="team", values="fcr_pct"),
              caption="fcr_pct by month x team (all teams, for contrast)")

    # --- Pattern 4: CSAT vs true sentiment ----------------------------------
    rep.text("\n### 4.4 CSAT vs true sentiment\n")
    sv = survey.merge(interactions[["interaction_id", "true_sentiment", "topic"]],
                      on="interaction_id")
    by_sent = sv.groupby("true_sentiment").agg(
        responses=("response_id", "size"),
        mean_csat=("csat_score", "mean"),
        pct_resolved_y=("resolved", lambda s: round((s == "Y").mean(), 3)),
        pct_blank_comment=("comment", lambda s: round((s.astype(str).str.strip() == "").mean(), 3)),
    ).round(2).reindex(["negative", "neutral", "positive"])
    rep.table(by_sent)

    means = by_sent["mean_csat"]
    rep.check("mean CSAT rises monotonically negative -> neutral -> positive",
              means["negative"] < means["neutral"] < means["positive"],
              " < ".join(f"{k} {v:.2f}" for k, v in means.items()))
    rep.check("CSAT gap between positive and negative is at least 1.5 points",
              means["positive"] - means["negative"] >= 1.5,
              f"{means['positive'] - means['negative']:.2f} points")
    rep.check("CSAT is noisy, not deterministic (scores overlap across sentiments)",
              sv.groupby("true_sentiment")["csat_score"].nunique().ge(3).all(),
              "each sentiment produces at least 3 distinct scores")

    # Non-response bias: the reason this project scores transcripts at all.
    rep.text("\n### 4.5 Survey non-response bias\n")
    resp = interactions.assign(responded=interactions["interaction_id"].isin(survey["interaction_id"]))
    rate_by_sent = resp.groupby("true_sentiment")["responded"].mean().round(3)
    bias = pd.DataFrame({
        "interactions": interactions["true_sentiment"].value_counts(),
        "population_share": interactions["true_sentiment"].value_counts(normalize=True).round(3),
        "response_rate": rate_by_sent,
        "respondent_share": sv["true_sentiment"].value_counts(normalize=True).round(3),
    }).reindex(["negative", "neutral", "positive"])
    rep.table(bias)

    rep.check("negative contacts respond to the survey more often than positive",
              rate_by_sent["negative"] > rate_by_sent["positive"],
              f"{pct(rate_by_sent['negative'])} vs {pct(rate_by_sent['positive'])}")
    rep.check("negatives are over-represented among respondents",
              bias.loc["negative", "respondent_share"] > bias.loc["negative", "population_share"],
              f"{pct(bias.loc['negative', 'respondent_share'])} of responses vs "
              f"{pct(bias.loc['negative', 'population_share'])} of contacts")

    # --- Pattern 5: repeat contact / escalation -----------------------------
    rep.text("\n### 4.6 Repeat contact and escalation\n")
    cj = cases.merge(interactions[["interaction_id", "true_sentiment"]], on="interaction_id")
    by_cs = cj.groupby("true_sentiment").agg(
        cases=("case_id", "size"),
        pct_repeat_7d=("repeat_contact_7d", lambda s: round((s == "Y").mean(), 3)),
        pct_escalated=("status", lambda s: round((s == "escalated").mean(), 3)),
    ).reindex(["negative", "neutral", "positive"])
    rep.table(by_cs)

    rep.check("negative contacts repeat more than positive ones",
              by_cs.loc["negative", "pct_repeat_7d"] > by_cs.loc["positive", "pct_repeat_7d"],
              f"{pct(by_cs.loc['negative', 'pct_repeat_7d'])} vs "
              f"{pct(by_cs.loc['positive', 'pct_repeat_7d'])}")
    rep.check("negative contacts escalate more than positive ones",
              by_cs.loc["negative", "pct_escalated"] > by_cs.loc["positive", "pct_escalated"],
              f"{pct(by_cs.loc['negative', 'pct_escalated'])} vs "
              f"{pct(by_cs.loc['positive', 'pct_escalated'])}")

    repeat_by_type = cases.groupby("case_type")["repeat_contact_7d"].apply(
        lambda s: round((s == "Y").mean(), 3))
    rep.check(f"'{WORST_TOPIC}' has the highest repeat-contact rate",
              repeat_by_type.idxmax() == WORST_TOPIC,
              f"highest = '{repeat_by_type.idxmax()}' at {pct(repeat_by_type.max())}")

    # --- Pattern 6: volume and channel mix ----------------------------------
    rep.text("\n### 4.7 Volume shape and channel mix\n")
    mix = pd.DataFrame({
        "actual": interactions["channel"].value_counts(normalize=True).round(3),
        "target": pd.Series(CHANNEL_TARGET),
    })
    mix["abs_diff_pp"] = ((mix["actual"] - mix["target"]) * 100).abs().round(1)
    mix.index.name = "channel"
    rep.table(mix, caption="Channel mix")

    worst_pp = mix["abs_diff_pp"].max()
    rep.check("channel mix is within 3pp of 65/25/10", worst_pp <= 3.0,
              f"largest gap {worst_pp}pp")

    dow = interactions["start_datetime"].dt.day_name().value_counts()
    dow = dow.reindex(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])
    dow.index.name = "weekday"
    rep.table(dow.rename("interactions").to_frame(), caption="Volume by weekday")
    rep.check("Monday is the busiest weekday", dow.idxmax() == "Monday",
              f"Monday {dow['Monday']} vs next-highest {dow.drop('Monday').max()}")

    monthly = interactions["start_datetime"].dt.to_period("M").value_counts().sort_index()
    monthly.index = monthly.index.astype(str)
    monthly.index.name = "month"
    rep.table(monthly.rename("interactions").to_frame(), caption="Volume by month")
    rep.text(
        "\n> Note: the generated window is the last 6 months (Apr-Oct 2026), so the "
        "January seasonality weighting in `generate_interactions.py` is present in the "
        "code but outside the window. Set `WINDOW_MONTHS = 12` to surface it.\n"
    )


# --- 4. Transcript safety ---------------------------------------------------

def check_transcripts(rep, interactions):
    rep.section("5. Transcript integrity and safety")

    texts = interactions["transcript_text"].astype(str)

    turn_counts = []
    bad_alternation = 0
    bad_prefix = 0
    for text in texts:
        lines = [ln for ln in text.split("\n") if ln.strip()]
        speakers = []
        for ln in lines:
            if ln.startswith("Agent:"):
                speakers.append("A")
            elif ln.startswith("Customer:"):
                speakers.append("C")
            else:
                bad_prefix += 1
        turn_counts.append(len(speakers))
        if any(a == b for a, b in zip(speakers, speakers[1:])):
            bad_alternation += 1

    turns = pd.Series(turn_counts)
    rep.check("every transcript line is labelled 'Agent:' or 'Customer:'", bad_prefix == 0,
              f"{bad_prefix} unlabelled lines")
    rep.check("speakers strictly alternate in every transcript", bad_alternation == 0,
              f"{bad_alternation} transcripts with consecutive same-speaker turns")
    rep.check("turn counts stay within the 6-14 contract", turns.between(6, 14).all(),
              f"min {turns.min()}, max {turns.max()}, mean {turns.mean():.1f}")

    # Safety: payment details must always be masked, never fabricated. A long
    # digit run is the signature of a card or bank number.
    long_digits = texts.str.contains(r"\d{13,19}", regex=True)
    rep.check("no card-length digit sequences anywhere in the transcripts",
              not long_digits.any(), f"{int(long_digits.sum())} transcripts")
    # Anything looking like a formatted card number (4 groups of 4) is also out.
    grouped = texts.str.contains(r"\b(?:\d{4}[ -]){3}\d{4}\b", regex=True)
    rep.check("no formatted card-number patterns (nnnn nnnn nnnn nnnn)",
              not grouped.any(), f"{int(grouped.sum())} transcripts")

    redacted = texts.str.contains(re.escape("[REDACTED]"))
    rep.check("[REDACTED] is used where payment details would appear",
              redacted.any(), f"{int(redacted.sum())} transcripts use the placeholder")

    # No real brand should ever appear; the fictional one should.
    brand = texts.str.contains("Prairie Sky Utilities")
    rep.check("the fictional brand appears (no real utility names)", brand.any(),
              f"{pct(brand.mean())} of transcripts name the fictional utility")

    stats = pd.DataFrame({
        "turns": [turns.min(), turns.median(), turns.max()],
        "characters": [texts.str.len().min(), texts.str.len().median(), texts.str.len().max()],
    }, index=pd.Index(["min", "median", "max"], name="stat"))
    rep.table(stats, caption="Transcript size")


def main():
    agents, interactions, cases, survey, sqm = load()

    rep = Report()
    check_row_counts(rep, agents, interactions, cases, survey, sqm)
    check_nulls(rep, agents, interactions, cases, survey, sqm)
    check_integrity(rep, agents, interactions, cases, survey, sqm)
    check_patterns(rep, agents, interactions, cases, survey, sqm)
    check_transcripts(rep, interactions)

    report = rep.render()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report)

    print(report)
    print(f"Report written to {REPORT_PATH}")

    if rep.failures:
        print(f"\n{len(rep.failures)} check(s) FAILED.")
        sys.exit(1)
    print(f"\nAll {len(rep.results)} checks passed.")


if __name__ == "__main__":
    main()
